import { render } from "@testing-library/react";
import RootLayout from "./layout";
import { Inter } from "next/font/google";
import "@testing-library/jest-dom";

jest.mock("next/font/google", () => ({
    Inter: jest.fn().mockReturnValue({
        className: "mocked-inter-font-class",
    }),
}));

describe("RootLayout", () => {
    it("renders children correctly", () => {
        const { getByText } = render(
            <RootLayout>
                <div>Hello, World!</div>
            </RootLayout>
        );

        expect(getByText("Hello, World!")).toBeInTheDocument();
    });

    it("applies the correct font class to the body", () => {
        const { container } = render(
            <RootLayout>
                <div>Test Content</div>
            </RootLayout>
        );

        expect(container.querySelector("body")).toHaveClass(
            "mocked-inter-font-class"
        );
    });

    // it("sets the correct metadata", () => {
    //     expect(metadata.title).toBe("Create Next App");
    //     expect(metadata.description).toBe("Generated by create next app");
    // });

    it("sets the language attribute on the html element", () => {
        const { container } = render(
            <RootLayout>
                <div>Test Content</div>
            </RootLayout>
        );

        expect(container.querySelector("html")).toHaveAttribute("lang", "en");
    });
});

// // app/__tests__/layout.test.tsx
// import { render, screen } from "@testing-library/react";
// import "@testing-library/jest-dom";
// import RootLayout from "./layout"; // Corrected import path
// import { Inter } from "next/font/google";

// // Mock the Inter font import to avoid actual network requests
// jest.mock("next/font/google", () => ({
//     Inter: jest.fn(() => ({ className: "mock-inter-class" })),
// }));

// describe("RootLayout", () => {
//     it("renders children correctly", () => {
//         render(<RootLayout>Test Child</RootLayout>);
//         expect(screen.getByText("Test Child")).toBeInTheDocument();
//     });
//     it("applies the Inter font class and renders children", () => {
//         // Render the RootLayout component with some children
//         render(
//             <RootLayout>
//                 <div>Test Child</div>
//             </RootLayout>
//         );

//         // Check if the body element has the correct class
//         expect(document.body.className).toBe("mock-inter-class");

//         // Check if the children are rendered correctly
//         const childElement = screen.getByText("Test Child");
//         expect(childElement).toBeInTheDocument();
//     });
// });
